 /*****************************************************************************
 ** File Name:  	TroutII_Com_Reg_config.h                                 *
 ** Author:         	Tiantian Yu                                          *
 ** DATE:           	07/04/2013                                           *
 ** Description:    	TroutII common register byte address define          *
 *****************************************************************************/

#ifndef TROUTII_COMMON_REG_DEFS_H
#define TROUTII_COMMON_REG_DEFS_H

#define   TROUT2_COM_HOST_BASE                           (0x00004000<<2) 


#define   TROUT2_COM_REG_INT_CLEAR                       (TROUT2_COM_HOST_BASE+(0x00<<2))
#define   TROUT2_COM_REG_WIFI_ERR_CLEAR                  (TROUT2_COM_HOST_BASE+(0x01<<2))
#define   TROUT2_COM_REG_INT_MASK                        (TROUT2_COM_HOST_BASE+(0x02<<2))
#define   TROUT2_COM_REG_WIFI_ERR_MASK                   (TROUT2_COM_HOST_BASE+(0x03<<2))
#define   TROUT2_COM_REG_INT_STAT                        (TROUT2_COM_HOST_BASE+(0x04<<2))
#define   TROUT2_COM_REG_WIFI_ERR_STAT                   (TROUT2_COM_HOST_BASE+(0x05<<2))
#define   TROUT2_COM_REG_INT_CTRL                        (TROUT2_COM_HOST_BASE+(0x06<<2))
#define   TROUT2_COM_REG_INT_2ARM7_CLEAR                 (TROUT2_COM_HOST_BASE+(0x07<<2))
#define   TROUT2_COM_REG_INT_2ARM7_MASK                  (TROUT2_COM_HOST_BASE+(0x08<<2))
#define   TROUT2_COM_REG_INT_2ARM7_STAT                  (TROUT2_COM_HOST_BASE+(0x09<<2))
#define   TROUT2_COM_REG_SOFT_GEN                        (TROUT2_COM_HOST_BASE+(0x0A<<2))
#define   TROUT2_COM_REG_WIFI_WAKEUP_CLEAR               (TROUT2_COM_HOST_BASE+(0x0B<<2))  
#define   TROUT2_COM_REG_HOST_INT_CLEAR                  (TROUT2_COM_HOST_BASE+(0x0C<<2))
#define   TROUT2_COM_REG_WIFI_INT_REG2                   (TROUT2_COM_HOST_BASE+(0x0D<<2))
#define   TROUT2_COM_REG_WIFI_INT_MASK                   (TROUT2_COM_HOST_BASE+(0x0E<<2))
#define   TROUT2_COM_REG_WIFI_INT_CLEAR                  (TROUT2_COM_HOST_BASE+(0x0F<<2))
#define   TROUT2_COM_REG_MODEM_CTRL                      (TROUT2_COM_HOST_BASE+(0x10<<2))
#define   TROUT2_COM_REG_RF_PARA_NUM                     (TROUT2_COM_HOST_BASE+(0x11<<2))
#define   TROUT2_COM_REG_RF_SPI_CTRL                     (TROUT2_COM_HOST_BASE+(0x12<<2))
#define   TROUT2_COM_REG_BT_IRAM_EN                      (TROUT2_COM_HOST_BASE+(0x13<<2))
#define   TROUT2_COM_REG_SDIO_TIMEOUT               			(TROUT2_COM_HOST_BASE+(0x14<<2))
#define   TROUT2_COM_REG_ARM7_CTRL                  			(TROUT2_COM_HOST_BASE+(0x15<<2))
#define   TROUT2_COM_REG_RFADI_DIR_SEL              			(TROUT2_COM_HOST_BASE+(0x16<<2))
#define   TROUT2_COM_REG_RFSPI_DIR_SEL              			(TROUT2_COM_HOST_BASE+(0x17<<2))
#define   TROUT2_COM_REG_RF_SOFT_RESET              			(TROUT2_COM_HOST_BASE+(0x18<<2))
#define   TROUT2_COM_REG_RF_SETTLE_TIME             			(TROUT2_COM_HOST_BASE+(0x20<<2))
#define   TROUT2_COM_REG_WIFI_TIME_SET              			(TROUT2_COM_HOST_BASE+(0x21<<2))
#define   TROUT2_COM_REG_BT_TIME_SET                			(TROUT2_COM_HOST_BASE+(0x22<<2))  
#define   TROUT2_COM_REG_WIFI_ACT_CTRL              			(TROUT2_COM_HOST_BASE+(0x23<<2))
#define   TROUT2_COM_REG_BT_ACT_CTRL                			(TROUT2_COM_HOST_BASE+(0x24<<2))
#define   TROUT2_COM_REG_SWITCH_MODE_CTRL           			(TROUT2_COM_HOST_BASE+(0x25<<2))
#define   TROUT2_COM_REG_SWITCH_ABORT_CTRL          			(TROUT2_COM_HOST_BASE+(0x26<<2))
#define   TROUT2_COM_REG_WIFI_AGC_CTRL              			(TROUT2_COM_HOST_BASE+(0x27<<2))
#define   TROUT2_COM_REG_CAPTURE_CTRL               			(TROUT2_COM_HOST_BASE+(0x28<<2))
#define   TROUT2_COM_REG_UPSAMPLE_CTRL              			(TROUT2_COM_HOST_BASE+(0x29<<2))
#define   TROUT2_COM_REG_SWITCH_PROTECT_CTRL        			(TROUT2_COM_HOST_BASE+(0x2A<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI0              			(TROUT2_COM_HOST_BASE+(0x30<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI1              			(TROUT2_COM_HOST_BASE+(0x31<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI2              			(TROUT2_COM_HOST_BASE+(0x32<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI3              			(TROUT2_COM_HOST_BASE+(0x33<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI4              			(TROUT2_COM_HOST_BASE+(0x34<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI5              			(TROUT2_COM_HOST_BASE+(0x35<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI6              			(TROUT2_COM_HOST_BASE+(0x36<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI7              			(TROUT2_COM_HOST_BASE+(0x37<<2))  
#define   TROUT2_COM_REG_RF_PARA_WIFI8              			(TROUT2_COM_HOST_BASE+(0x38<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI9              			(TROUT2_COM_HOST_BASE+(0x39<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI10             			(TROUT2_COM_HOST_BASE+(0x3A<<2))
#define   TROUT2_COM_REG_RF_PARA_WIFI11             			(TROUT2_COM_HOST_BASE+(0x3B<<2))
#define   TROUT2_COM_REG_RF_PARA_BT0                			(TROUT2_COM_HOST_BASE+(0x40<<2))
#define   TROUT2_COM_REG_RF_PARA_BT1                			(TROUT2_COM_HOST_BASE+(0x41<<2))
#define   TROUT2_COM_REG_RF_PARA_BT2                			(TROUT2_COM_HOST_BASE+(0x42<<2))
#define   TROUT2_COM_REG_RF_PARA_BT3                			(TROUT2_COM_HOST_BASE+(0x43<<2))
#define   TROUT2_COM_REG_RF_PARA_BT4                			(TROUT2_COM_HOST_BASE+(0x44<<2))
#define   TROUT2_COM_REG_RF_PARA_BT5                			(TROUT2_COM_HOST_BASE+(0x45<<2))
#define   TROUT2_COM_REG_RF_PARA_BT6                			(TROUT2_COM_HOST_BASE+(0x46<<2))
#define   TROUT2_COM_REG_RF_PARA_BT7                			(TROUT2_COM_HOST_BASE+(0x47<<2))
#define   TROUT2_COM_REG_RF_PARA_BT8                			(TROUT2_COM_HOST_BASE+(0x48<<2))
#define   TROUT2_COM_REG_RF_PARA_BT9                			(TROUT2_COM_HOST_BASE+(0x49<<2))
#define   TROUT2_COM_REG_RF_PARA_BT10               			(TROUT2_COM_HOST_BASE+(0x4A<<2))
#define   TROUT2_COM_REG_RF_PARA_BT11               			(TROUT2_COM_HOST_BASE+(0x4B<<2))  
#define   TROUT2_COM_REG_WIFI_SHRAM_REVERSE_W            (TROUT2_COM_HOST_BASE+(0x50<<2))
#define   TROUT2_COM_REG_WIFI_SHRAM_REVERSE_R            (TROUT2_COM_HOST_BASE+(0x51<<2))
#define   TROUT2_COM_REG_ARM7_SHRAM_REVERSE_W            (TROUT2_COM_HOST_BASE+(0x52<<2))
#define   TROUT2_COM_REG_ARM7_SHRAM_REVERSE_R            (TROUT2_COM_HOST_BASE+(0x53<<2))
#define   TROUT2_COM_REG_INFO0_FROM_HOST                 (TROUT2_COM_HOST_BASE+(0x60<<2))
#define   TROUT2_COM_REG_INFO1_FROM_HOST                 (TROUT2_COM_HOST_BASE+(0x61<<2))        
#define   TROUT2_COM_REG_INFO2_FROM_HOST                 (TROUT2_COM_HOST_BASE+(0x62<<2))
#define   TROUT2_COM_REG_INFO3_FROM_HOST                 (TROUT2_COM_HOST_BASE+(0x63<<2))
#define   TROUT2_COM_REG_ARM2HOST_INFO0                  (TROUT2_COM_HOST_BASE+(0x64<<2))
#define   TROUT2_COM_REG_ARM2HOST_INFO1                  (TROUT2_COM_HOST_BASE+(0x65<<2))
#define   TROUT2_COM_REG_ARM2HOST_INFO2                  (TROUT2_COM_HOST_BASE+(0x66<<2))
#define   TROUT2_COM_REG_ARM2HOST_INFO3                  (TROUT2_COM_HOST_BASE+(0x67<<2))
#define   TROUT2_COM_REG_TEST_LOOP                       (TROUT2_COM_HOST_BASE+(0x70<<2))
#define   TROUT2_COM_REG_DFT_CTRL                        (TROUT2_COM_HOST_BASE+(0x71<<2))
#define   TROUT2_COM_REG_DFT_WAVE_CTRL              			(TROUT2_COM_HOST_BASE+(0x72<<2))
#define   TROUT2_COM_REG_DFT_DAC_REG                			(TROUT2_COM_HOST_BASE+(0x73<<2))  
#define   TROUT2_COM_REG_DFT_ADC_REG               			(TROUT2_COM_HOST_BASE+(0x74<<2))
#define   TROUT2_COM_REG_CHIP_MX                    			(TROUT2_COM_HOST_BASE+(0x0FF<<2))
#define   TROUT2_COM_REG_ARM2HOST_INFO0             			(TROUT2_COM_HOST_BASE+(0x64<<2))
#define   TROUT2_COM_REG_ARM2HOST_INFO1             			(TROUT2_COM_HOST_BASE+(0x65<<2))

#endif //TROUTII_COMMON_REG_DEFS_H
