
trace:
	perl trace_tool.pl 1 Common Controller Core CSL Edge Library Test Utils

untrace:
#	cp /mnt/hgfs/share/itm_trace.log /mnt/hgfs/share/ittiam_wlan/ittiam_wlan_src/trace_tool
	perl trace_tool.pl 2 1 0 0
