
obj-$(CONFIG_FB_SC8810) := sprdfb_main.o lcdpanel.o lcdc.o

obj-$(CONFIG_FB_LCD_HX8369) += lcd_hx8369.o

obj-$(CONFIG_FB_LCD_HX8357) += lcd_hx8357_1.o
obj-$(CONFIG_FB_LCD_ILI9486) += lcd_ili9486.o
obj-$(CONFIG_FB_LCD_HX8357_OPENPHONE) += lcd_hx8357_openphone.o
obj-$(CONFIG_FB_LCD_RM6158_TRULY) += lcd_rm6158_truly.o
obj-$(CONFIG_FB_LCD_NT35516) += lcd_nt35516.o
obj-$(CONFIG_FB_LCD_ILI9341_BOE) += lcd_ili9341_boe.o
obj-$(CONFIG_FB_LCD_ILI9341_BOE_MINT) += lcd_ili9341_boe_mint.o
obj-y += lcd_nt35510.o
obj-$(CONFIG_FB_LCD_S6D04H0) += lcd_s6d04h0.o
obj-$(CONFIG_FB_LCD_ILI9481) += lcd_ili9481.o
obj-$(CONFIG_FB_LCD_NT35310) += lcd_nt35310.o
obj-$(CONFIG_FB_LCD_HX8357D) += lcd_hx8357d.o
obj-$(CONFIG_FB_LCD_ST7796S) += lcd_st7796s.o
obj-$(CONFIG_FB_LCD_ILI9488) += lcd_ili9488.o
obj-$(CONFIG_FB_LCD_R61581B) += lcd_r61581b.o
